name: glint_frontend
description: "FE works for the Glint Products"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_xlider: ^3.5.0
  flutter_card_swiper: ^7.0.2
  bottom_picker: ^2.9.0
  dotted_line: ^3.2.3
  image_picker: ^1.1.2
  gradient_circular_progress_indicator: ^0.0.4
  carousel_slider: ^5.0.0
  stream_chat_flutter: ^9.2.0+1
  stream_chat_flutter_core: ^9.2.0
  story: ^1.1.0
  pinput: ^5.0.1
  dio: ^5.8.0+1
  encrypt_shared_preferences: ^0.8.6
  floor: ^1.5.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  rxdart: ^0.28.0
  logging: ^1.3.0
  floor_generator: ^1.5.0
#  flutter_secure_storage: ^4.2.1
  razorpay_flutter: ^1.4.0
  intl: 0.19.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  crypto: ^3.0.6
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  stream_chat_localizations: ^9.8.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  permission_handler: 12.0.0
  file_picker: ^10.1.9
  image: ^4.5.4
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/images/chat/
    - lib/assets/icons/
    - lib/assets/images/onboarding/
    - lib/assets/icons/profile/
    - lib/assets/icons/admin/
    - lib/assets/images/event/
    - lib/assets/images/auth/
    - lib/assets/images/admin/
    - lib/assets/animation/

  fonts:
    - family: AlbertSans
      fonts:
        - asset: lib/assets/fonts/AlbertSans_regular.ttf
        - asset: lib/assets/fonts/AlbertSans-Bold.ttf
          weight: 700
    - family: Cambon
      fonts:
        - asset: lib/assets/fonts/Cambon-Light.ttf
        - asset: lib/assets/fonts/Cambon-MediumItalic.ttf
        - asset: lib/assets/fonts/Cambon-SemiBoldItalic.ttf
        - asset: lib/assets/fonts/Cambon-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Cambon-BoldItalic.ttf
          weight: 700
        - asset: lib/assets/fonts/Cambon-BlackItalic.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/glint-app-icon.png"
  min_sdk_android: 21